### ISSUE TITLE
JavaConversions vs. JavaConverters

### ISSUE THREAD

**Issue by TomasMikula** [leifwickland/static-analysis-skeleton#1]
Hi Leif, thanks for this skeleton and the slides!

On the slide _"Linter Also Found"_ you have
- Use JavaConversions, not JavaConverters

but in my case Linter actually reported the opposite:

> Consider using the explicit collection.JavaConverters instead of implicit conversions in collection.JavaConversions.

So is this a typo in the slides?

**Comment by leifwickland** [comment]
Tomas,

I'm really glad you found the infomation useful. 

Yeah, that was a question of how the slides should read.  I was trying to say "Linter said that I was using Conversions, not Conversions" which probably comes across as "Linter says I should use the bad thing, not the good thing."  The rest of the bullet points on the slide are phrased similarly, i.e. they list the practice to avoid. For symmetry I went the route you see.  Ironically the wording on the slide tripped me up in my talk, too. 

Thanks for the feedback!  Please let me know if you think I should change any of the recommendations.

Thanks,

Leif

**Comment by TomasMikula** [comment]
Oh, OK :)
